/* jshint -W101 */

var language_enUS = {
	"GENERAL": {
		"FOLLOWERS": "Followers",
		"BY": "By",
		"DISPLAY_BY": "Display by",
		"CREATE_SPOT": "Create a new spot",
		"VIEW_SPOT": "Display spot",
		"LOADMORE_SPOTS": "load more",
		"FIND_WANT": "Find this want",
		"NOT_CONNECTED": "You are not connected",
		"NEED_CONNECTED": "You must be connected",
	},
	"HEADER": {
		"HEADER_TITLE": "Spotern",
		"HEADER_DESC": "Welcome"
	},
	"BANDEAU": {
		"BUTTON_CONNECT": "Login",
		"BUTTON_SEARCH": "Search",
		"BUTTON_NEWSPOT": "Create a spot"
	},
	"BOXES": {
		"BOX_CONNECT_TITLE": "Welcome to Spotern !"
	}
};

var language_frFR = {
	"GENERAL": {
		"FOLLOWERS": "Abonnés",
		"BY": "Par",
		"DISPLAY_BY": "Afficher par",
		"CREATE_SPOT": "Créer un spot",
		"VIEW_SPOT": "Voir le spot",
		"FIND_WANT": "Trouvons-le !",
		"LOADMORE_SPOTS": "encore plus de spots",
		"NOT_CONNECTED": "Vous n'êtes pas connecté.",
		"NEED_CONNECTED": "Vous devez être connecté",
		"BUY": "Acheter",
		"TAGS": "Tags",
		"MOVIE": "Film",
		"TV": "TV",
		"ACTORS": "Acteurs",
		"DISPLAY_SPOT": "Afficher le spot",
		"USERS": "Utilisateurs",
		"ADD_TAG": "Ajouter un tag",
		"CANCEL": "Annuler",
	},
	"HEADER": {
		"HEADER_TITLE": "Spotern",
		"HEADER_DESC": "Bienvenue"
	},
	"BANDEAU": {
		"BUTTON_CONNECT": "se connecter",
		"BUTTON_SEARCH": "recherche",
		"BUTTON_NEWSPOT": "crée un spot"
	},
	"NOTIFICATION": {
		"LIKE": "{{value}} a aimé votre spot",
		"ALERT": "{{value}} a signalé un lien mort",
	},
	"PARAMS": {
		"SAVED": "Données sauvegardées",
	},
	"BOXES": {
		"BOX_CONNECT_TITLE": "Bienvenue sur Spotern !"
	},
	"SPOTMAKER": {
		"VERIFY_FIELDS": "Verifier les champs obligatoires",
		"CREATE": "Créer",
		"CREATE_COLLECTION": "Créer une nouvelle collection",
		"SPOTNAME_TOO_SHORT": "Le nom du spot doit être supérieur à 4 caractères",
		"COMPLETE": "Le spot vient d'être ajouté",
		"CANT_UPLOAD_IMAGE": "Une erreur est survenue lors de l'enregistrement de l'image du spot",
		"CANT_CREATE_SPOT": "Une erreur est survenue lors de l'enregistrement du spot",
		"CANT_CREATE_PRODUCT": "Une erreur est survenue lors de l'enregistrement des données du produit associé au spot",
		"UPLOAD_IN_PROGRESS": "Envoi des données du spot en cours",
		"VALIDATE_STEP": "Valider cette étape",
	},
	"COLLECTIONS": {
		"FOLLOW_TITLE": "Suivre cette collection",
		"FOLLOW": "Désormais vous suivez cette collection",
		"FOLLOW_LINK": "Suivre cette collection",
		"NEED_CONNECTED_FOLLOW": "Vous devez être connecté pour suivre une collection",
		"NEED_CONNECTED_LIKE": "Vous devez être connecté pour aimer une collection",
		"LIKE": "Vous aimez désormais cette collection !",
		"SPOT_REMOVED": "Le spot a bien été supprimé de la collection",
	},
	"SPOT": {
		"PRODUCT_DESCRIPTION": "Descriptif produit",
		"DISPLAY_SPOT_OF": "Afficher les spots de ",
		"SIMILAR_SPOTS": "Spots similaires",
		"NEED_CONNECTED_LIKE": "Vous devez être connecté pour aimer un spot",
		"LIKE": "Vous aimez désormais ce spot !",
		"ALERT": "Le créateur du spot est informé d'une erreur, merci !",
		"NEED_CONNECTED_ALERT": "Vous devez être connecté pour signaler une erreur",
		"UPDATE_NAME": "Mise à jour du nom du spot effectuée",
		"UPDATE_NAME_ERROR": "Une erreur est survenue lors de la mise à jour du nom du spot",
		"UPDATE_TAGS": "Mise à jour des tags du spot effectuée",
		"UPDATE_TAGS_ERROR": "Une erreur est survenue lors de la mise à jour des tags du spot",
		"UPDATE_MEDIA_BUTTON": "Modifier le média",
	},
	"WANTED": {
		"NEED_YOU": "On a besoin de vous !",
		"NEED_YOU_AUTHOR": "{{name}} aimerait trouver le produit correspondant à son wanted.",
		"ADD_PRODUCT": "Associer un produit",
		"MESSAGE": "Son message",
	},
	"USER": {
		"LOST_PASSWORD_ERROR": "Vous avez fait trop de demande de récupération de mot de passe",
	},
	"ERRORS": {
		"E0001": "Vous n'être pas connecté !",
		"E0002": "La connection à expiré",
		"E0003": "Format JSON attendu incorrect",
		"E0004": "Email non envoyé",
		"E0005": "Format d'un champ invalide",
		"E0050": "Adresse email manquante",
		"E0051": "Username manquant",
		"E0052": "Lastname manquant",
		"E0053": "Firstname manquant",
		"E0054": "Password manquant",
		"E0055": "Adresse email attendue",
		"E0056": "Mot de passe trop court",
		"E0057": "Userid manquant",
		"E0058": "Entier attendu",
		"E0059": "Utilisateur inconnu",
		"E0060": "Image manquante",
		"E0061": "URL attendue",
		"E0062": "Identifiant de site web manquant",
		"E0063": "Nom de collection manquant",
		"E0064": "Description de collection manquant",
		"E0065": "Identifant de collection manquant",
		"E0066": "Type manquant",
		"E0067": "Tableau attendu",
		"E0068": "Query manquant",
		"E0069": "Erreur dans la recherche de media",
		"E0070": "Identifiant TMDB manquant",
		"E0071": "Type de média manquant",
		"E0072": "Langue manquante",
		"E0073": "Mauvais code langue",
		"E0074": "Mauvais type de média",
		"E0075": "Manque l'identifiant média",
		"E0076": "Nom de spot trop court",
		"E0077": "ExactMatch manquant",
		"E0078": "Booléen attendu",
		"E0079": "ImageAllowSpotern manquant",
		"E0080": "URL ou texte du wanted manquant",
		"E0081": "ImageSpotX manquant",
		"E0082": "ImageSpotY manquant",
		"E0083": "Image inaccessible",
		"E0084": "Mauvaise saison/épisode",
		"E0085": "Identifiant de spot manquant",
		"E0086": "Spot inconnu",
		"E0087": "Spot non associé à l'utilisateur identifié",
		"E0088": "Pas assez de caractères",
		"E0089": "Mauvais type de spot",
		"E0090": "Chaine de caractères attendue",
		"E0091": "Manque chaine de recherche",
		"E0092": "Manque l'ordre de tri",
		"E0093": "Mauvais type d'ordre",
		"E0100": "Authentification incorrect",
		"E0110": "Username non utilisé",
		"E0120": "Email non utilisé",
		"E0130": "Email déjà utilisé",
		"E0131": "Username déjà utilisé",
		"E0132": "Utilisateur non ajouté",
		"E0133": "Le code d'invitation n'est pas valide ou déjà utilisé",
		"E0140": "Pas de token d'activation fourni",
		"E0141": "Utilisateur inconnu",
		"E0142": "Erreur à l'activation de l'utilisateur",
		"E0150": "Utilisateur inconnu",
		"E0160": "Changement d'email impossible",
		"E0161": "Changement de username impossible",
		"E0162": "Pas de mise a jour nécessaire",
		"E0163": "Erreur lors de la mise a jour des données",
		"E0170": "Ne peut pas enregistrer l'avatar",
		"E0180": "Ne peut pas enregistrer l'image de couverture",
		"E0190": "Ne peut pas ajouter un site web",
		"E0200": "Ne peut pas supprimer un site web",
		"E0210": "Ne peut pas récupérer la liste de collections",
		"E0220": "Ne peut pas ajouter une collection",
		"E0230": "Impossible de sauvegarder les données de votre collection",
		"E0240": "Ne peut pas effacer la collection",
		"E0250": "Cette collection n'appartient à l'utilisateur connecté",
		"E0251": "Ne peut pas sauvegarder l'image de couverture de la collection",
		"E0260": "Ne peut pas récupérer la liste des notifications",
		"E0270": "Ne peut pas accuser réception des notifications",
		"E0280": "Identifiant de notification manquant",
		"E0281": "Ne peut pas effacer la notification",
		"E0290": "Ne peut pas effacer les notifications",
		"E0300": "Ne peut pas ajouter le média",
		"E0310": "Ne peut pas récupérer le média",
		"E0320": "Ne peut pas récupérer la saison de la série TV",
		"E0330": "Ce spot existe déjà",
		"E0331": "Ne peut pas ajouter le spot",
		"E0332": "ProductID inconnu",
		"E0340": "Ne peut pas sauvegarder l'image du spot",
		"E0350": "Nom de tag manquant",
		"E0351": "Ne peut pas récupérer une liste de tags",
		"E0352": "Pas de résultat",
		"E0360": "Ne peut pas récupérer le spot",
		"E0370": "Ne peut pas like ce spot",
		"E0380": "Ne peut pas mettre à jour le spot",
		"E0390": "Ne peut pas unlike ce spot",
		"E0400": "Le spot n'a pas le statut wanted",
		"E0401": "URL manquante",
		"E0402": "Ne peut pas ajouter la résolution du spot",
		"E0410": "Ne peut pas récupérer la résolution du spot",
		"E0420": "Ne peut pas effacer les résolutions du spot",
		"E0430": "Ne peut pas récupérer la liste de spot",
		"E0440": "Ne peut pas rechercher un spot",
		"E0491": "Cette collection vous appartient, vous ne pouvez pas la suivre",
		"E0492": "Vous suivez déjà cette collection",
	}
};
